server:
  port: 9001
spring:
  application:
    name: item-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.68.128:8848
        username: nacos
        password: Zhc20050105@
    openfeign:
      okhttp:
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8090
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${hm.db.host:localhost}:${hm.db.port:3306}/${hm.db.dbname}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${hm.db.um:root}
    password: ${hm.db.pw:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

#seata:
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 192.168.68.128:8848
#      namespace: ""
#      group: DEFAULT_GROUP
#      application: seata-server
#      username: nacos
#      password: Zhc20050105@
#  tx-service-group: hmall
#  service:
#    vgroup-mapping:
#      hmall: "default"
#  data-source-proxy-mode: AT

seata:
  enabled: true
  application-id: ${spring.application.name}  # 通常与Spring应用名保持一致
  tx-service-group: hmall # 自定义事务分组名称,需与vgroup-mapping的key对应
  service:
    vgroup-mapping:
      hmall: default # 将事务分组映射到默认集群
    grouplist:
      default: 192.168.68.128:8099   # 改成你 Seata Server 的实际 IP:端口
  registry:
    type: file
  config:
    type: file
  data-source-proxy-mode: AT


mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto


logging:
  level:
    com.george.item: info
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: logs/${spring.application.name}