server:
  port: 9001
spring:
  application:
    name: item-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.41.128:8848
        username: nacos
        password: Zhc20050105@
    openfeign:
      okhttp:
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8090
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${hm.db.host:localhost}:${hm.db.port:3306}/${hm.db.dbname}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${hm.db.um:root}
    password: ${hm.db.pw:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto


logging:
  level:
    com.george.item: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: logs/${spring.application.name}