server:
  port: 9006
spring:
  application:
    name: trade-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.41.128:8848
      config:
        server-addr: 192.168.41.128:8848
        file-extension: yaml
    openfeign:
      okhttp:
        enabled: true
  profiles:
    active: local

  config:
    import:
      - optional:nacos:jdbc.yaml
      - optional:nacos:log.yaml



